spring.application.name=inv
spring.datasource.url=jdbc:postgresql://localhost:5432/nodo_inv
spring.datasource.username=postgres
spring.datasource.password=123456

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jackson.serialization.fail-on-empty-beans=false

jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
jwt.expiration=28800000

spring.cache.type=caffeine
spring.cache.caffeine.spec=expireAfterWrite=12h,maximumSize=500

